# BESI-C Automatic Updater
#   https://github.com/besi-c/besic-scripts
#   Penn Bauman <pcb8gb@virginia.edu>
prefix = /usr/local
bindir = $(prefix)/bin

install:
	install -m 0755 -d $(DESTDIR)$(bindir)
	install -m 0755 autoupdates.sh $(DESTDIR)$(bindir)/besic-autoupdates
