# BESI-C Data Uploader for AWS S3
#   https://github.com/besi-c/besic-scripts
#   Penn Bauman <pcb8gb@virginia.edu>
prefix = /usr/local
bindir = $(prefix)/bin

install:
	install -m 0755 -d $(DESTDIR)$(bindir)
	install -m 0755 s3upload.py $(DESTDIR)$(bindir)/besic-s3upload
