prefix = /usr/local

install:
	mkdir -p $(DESTDIR)$(prefix)/bin
	install -T announce.sh $(DESTDIR)$(prefix)/bin/besic-announce
	install -T heartbeat.sh $(DESTDIR)$(prefix)/bin/besic-heartbeat
	install -T update.sh $(DESTDIR)$(prefix)/bin/besic-update
